# Generated by Django 5.1.2 on 2025-01-02 10:24

import uuid
from django.conf import settings
from django.db import migrations, models

def generate_uuids(apps, schema_editor):
    Thread = apps.get_model('egthreads', 'Thread')
    for thread in Thread.objects.all():
        thread.uuid = uuid.uuid4()
        thread.save()

class Migration(migrations.Migration):

    dependencies = [
        ('egthreads', '0002_thread_is_deleted'),
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['uuid'], name='egthreads_t_uuid_a21e74_idx'),
        ),
        migrations.RunPython(generate_uuids),
    ]
