# Generated by Django 5.1.2 on 2025-01-02 10:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egthreads', '0003_thread_uuid_thread_egthreads_t_uuid_a21e74_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
