# Generated by Django 5.1.2 on 2025-01-02 11:11

import egthreads.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egthreads', '0004_alter_thread_uuid'),
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='thread',
            name='egthreads_t_uuid_a21e74_idx',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='uuid',
        ),
        migrations.AddField(
            model_name='thread',
            name='thread_id',
            field=models.CharField(default=egthreads.models.generate_thread_id, max_length=9),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['thread_id'], name='egthreads_t_thread__457024_idx'),
        ),
    ]
