# Generated by Django 5.1.2 on 2025-01-02 11:15

import egthreads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egthreads', '0005_remove_thread_egthreads_t_uuid_a21e74_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='thread_id',
            field=models.CharField(default=egthreads.models.generate_thread_id, max_length=9, unique=True),
        ),
    ]
