# Generated by Django 5.1.2 on 2026-04-07 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_convers_3154fc_idx',
            old_name='chat_message_convers_6c93be_idx',
        ),
    ]
